#define USE_UNITASK //TODO: REMOVE THIS!!!
using System;
using System.Collections;
using System.Collections.Generic;
using System.Threading;
using UnityEngine;
using UnityEngine.Events;
using Random = UnityEngine.Random;

#if USE_UNITASK
using Cysharp.Threading.Tasks;
#endif

[RequireComponent(typeof(AudioSourcePoolingService))]
public class AudioManagerDynamic : MonoBehaviour
{
    [Header("Settings Data")]
    [SerializeField] private AudioManagerSettings audioManagerSettings;
    [Space]

    [Header("Services")]
    //private AudioManagerDataService audioManagerDataService;
    private AudioSourcePoolingService sourceProvider;
    [Space]

    [SerializeField] private AudioVolumesTransferObject transferObject;
    [Space]

    private AudioListener audioListener;
    private AudioPauseService audioPauseService;
    private AudioManagerDictionaryProvider dictionaryProvider;


    //    [Header("General Values for both Methods")]
    //    [SerializeField][Range(1, 100)] private int numbersOfAudioSources = 50;
    //    [SerializeField] private float defaultCuttoffFreqValue = 5000f;
    //    [SerializeField] private GameObject audioGameObjectPrefab;
    //    [SerializeField] private CutoffFreqLayerBehaviour[] CutoffFrequenciesPerLayer;
    //    [SerializeField] private Transform playerAudioListenerTransform;
    //    [SerializeField][Range(0.01f, 1f)] private float timeIntervalBetweenPositionChecks = 0.25f;

    //    private LayerMask autoGeneratedWallLayerMask;


    public static UnityAction<AudioDataObject> CallAudioSourceDispatcher;
    public static UnityAction<AudioDataObject> DynamicAudioSourceStop;
    public static UnityAction CallPauseAllSources;
    public static UnityAction CallUnPauseAllSources;


#if !USE_UNITASK
        [Header("Coroutine specific values")]
        private readonly Dictionary<int, Coroutine> activeCoroutineChecks = new Dictionary<int, Coroutine>();
        private WaitForSeconds intervalWait;
        private WaitForSeconds pauseWait;
#else
    [Header("UniTask specific values")]
    private CancellationTokenSource linkedMasterTokenSource;
#endif

    private void Awake()
    {
        audioListener = FindFirstObjectByType<AudioListener>(); // only called once
        audioManagerSettings.playerAudioListenerTransform = audioListener.gameObject.transform;

        sourceProvider = GetComponent<AudioSourcePoolingService>();
        dictionaryProvider = new();

#if !USE_UNITASK
        audioManagerSettings.intervalWait = new WaitForSeconds(audioManagerSettings.timeIntervalBetweenPositionChecks);
        audioManagerSettings.pauseWait = new WaitForSeconds(0.1f);
        Debug.Log("[AudioTool] Pure Coroutine mode initialized (Not Recommended).");
#else

        linkedMasterTokenSource = new CancellationTokenSource();
        Debug.Log("[AudioTool] UniTask mode initialized (Recommended).");
#endif
        //Initialize all services
       audioPauseService = new(sourceProvider.allAudioSources);
    }

    private void OnEnable()
    {
        CallAudioSourceDispatcher += AquireAudioSource;
        DynamicAudioSourceStop += StopCurrentAudioSource;

        CallPauseAllSources += audioPauseService.PauseAllSources;
        CallUnPauseAllSources += audioPauseService.UnpauseAllSources;
    }

    private void Start()
    {
        dictionaryProvider.FillLayerMaskDictionaryWithLayerRelatedValues(audioManagerSettings.CutoffFrequenciesPerLayer);
        dictionaryProvider.FillDictionaryWithKeysAndValues(transferObject);

        GenerateLayerMaskFromDictionary();
    }

    private void OnDisable()
    {
        CallAudioSourceDispatcher -= AquireAudioSource;
        DynamicAudioSourceStop -= StopCurrentAudioSource;

        CallPauseAllSources -= audioPauseService.PauseAllSources;
        CallUnPauseAllSources -= audioPauseService.UnpauseAllSources;
    }


    private void AquireAudioSource(AudioDataObject _audioDataObject)
    {
        int poolIndex = sourceProvider.GetFreeAudioSourcePoolIndex();
        if (poolIndex == -1) return;

        _audioDataObject.PoolIndex = poolIndex;

        AudioObject poolObject = sourceProvider.allAudioSources[poolIndex];
        AudioSource source = poolObject.Source;
        AudioLowPassFilter filter = poolObject.Filter;

        source.clip = _audioDataObject.CurrentClips[Random.Range(0, _audioDataObject.CurrentClips.Length)];

        if (dictionaryProvider.volumeDictionary.TryGetValue(_audioDataObject.CurrentType, out float curVolume))
            source.volume = curVolume;

        if (_audioDataObject.SetCallerAsParent)
        {
            poolObject.GameObject.transform.SetParent(_audioDataObject.CallerTransform);
            poolObject.GameObject.transform.position = _audioDataObject.CallerTransform.position;
        }
        else
            poolObject.GameObject.transform.position = _audioDataObject.CallerTransform.position;

        filter.cutoffFrequency = audioManagerSettings.defaultCuttoffFreqValue;


#if !USE_UNITASK
        StartWallCheckCoroutine(sourceProvider,_audioDataObject, filter, source.clip.length, poolIndex);
#else
        StartWallCheckUniTask(sourceProvider, _audioDataObject, filter, source.clip.length, poolIndex);
#endif
        source.Play();
    }

#if !USE_UNITASK
    private void StartWallCheckCoroutine(AudioSourcePoolingService sourceProvider, AudioDataObject audioDataObject, AudioLowPassFilter filter, float currentClipLength, int poolIndex)
    {
        if (audioManagerSettings.activeCoroutineChecks.TryGetValue(poolIndex, out Coroutine runningCoroutine))
        {
            if (runningCoroutine != null) StopCoroutine(runningCoroutine);
            audioManagerSettings.activeCoroutineChecks.Remove(poolIndex);
        }

        Coroutine newCheck = StartCoroutine(CheckIfPlayerBehindWallRoutine(audioDataObject, filter, currentClipLength, poolIndex));
        audioManagerSettings.activeCoroutineChecks.Add(poolIndex, newCheck);
    }

    private IEnumerator CheckIfPlayerBehindWallRoutine(AudioDataObject audioDataObject, AudioLowPassFilter filter, float currentClipLength, int poolIndex)
    {
        float elapsedPlayTime = 0f;
        AudioSource targetSource = sourceProvider.allAudioSources[poolIndex].Source;

        if (CheckIfPlayerIsBehindWall(audioDataObject, out RaycastHit firstHit))
            AssignNewCutoffFreqToCurrentSource(filter, firstHit);

        while (elapsedPlayTime < currentClipLength)
        {
            if (audioDataObject == null || targetSource == null) yield break;

            if (!targetSource.isPlaying)
            {
                yield return audioManagerSettings.pauseWait;
                continue;
            }

            if (CheckIfPlayerIsBehindWall(audioDataObject, out RaycastHit tempHit))
                AssignNewCutoffFreqToCurrentSource(filter, tempHit);

            else if (filter != null)
                filter.cutoffFrequency = audioManagerSettings.defaultCuttoffFreqValue;

            yield return audioManagerSettings.intervalWait;
            elapsedPlayTime += audioManagerSettings.timeIntervalBetweenPositionChecks;
        }

        if (audioDataObject != null) audioDataObject.PoolIndex = -1;
        audioManagerSettings.activeCoroutineChecks.Remove(poolIndex);
    }
#endif


#if USE_UNITASK
    private void StartWallCheckUniTask(AudioSourcePoolingService sourceProvider, AudioDataObject _audioDataObject, AudioLowPassFilter _filter, float _currentClipLength, int _poolIndex)
    {
        sourceProvider.poolTokenSources[_poolIndex].Cancel();
        sourceProvider.poolTokenSources[_poolIndex].Dispose();
        sourceProvider.poolTokenSources[_poolIndex] = CancellationTokenSource.CreateLinkedTokenSource(linkedMasterTokenSource.Token);

        CheckIfPlayerBehindWallUniTaskVoid(
            sourceProvider.poolTokenSources[_poolIndex].Token,
            _audioDataObject,
            _filter,
            _currentClipLength,
            _poolIndex
        ).Forget();
    }

    private async UniTaskVoid CheckIfPlayerBehindWallUniTaskVoid(CancellationToken _token, AudioDataObject _audioDataObject, AudioLowPassFilter _filter, float _currentClipLength, int _poolIndex)
    {
        float elapsedPlayTime = 0f;
        AudioSource targetSource = sourceProvider.allAudioSources[_poolIndex].Source;
        int checkIntervalMs = (int)(audioManagerSettings.timeIntervalBetweenPositionChecks * 1000);

        if (CheckIfPlayerIsBehindWall(_audioDataObject, out RaycastHit firstHit))
            AssignNewCutoffFreqToCurrentSource(_filter, firstHit);

        while (elapsedPlayTime < _currentClipLength)
        {
            if (_token.IsCancellationRequested) return;
            if (_audioDataObject == null || targetSource == null) return;

            if (!targetSource.isPlaying)
            {
                bool isCanceled = await UniTask.Delay(100, delayType: DelayType.DeltaTime, cancellationToken: _token).SuppressCancellationThrow();
                if (isCanceled) return;
                continue;
            }

            if (CheckIfPlayerIsBehindWall(_audioDataObject, out RaycastHit tempHit))
                AssignNewCutoffFreqToCurrentSource(_filter, tempHit);

            else if (_filter != null)
                _filter.cutoffFrequency = audioManagerSettings.defaultCuttoffFreqValue;

            bool canceledDuringWait = await UniTask.Delay(checkIntervalMs, delayType: DelayType.DeltaTime, cancellationToken: _token).SuppressCancellationThrow();
            if (canceledDuringWait) return;

            elapsedPlayTime += audioManagerSettings.timeIntervalBetweenPositionChecks;
        }

        if (_audioDataObject != null) _audioDataObject.PoolIndex = -1;
    }
#endif

    private bool CheckIfPlayerIsBehindWall(AudioDataObject _audioDataObject, out RaycastHit hitinfo)
    {
        hitinfo = default;

        if (audioManagerSettings.playerAudioListenerTransform == null || _audioDataObject == null || _audioDataObject.CallerTransform == null)
            return false;

        Vector3 startPos = _audioDataObject.CallerTransform.position;
        Vector3 direction = audioManagerSettings.playerAudioListenerTransform.position - startPos;
        float maxDistance = direction.magnitude;

        if (Physics.Raycast(startPos, direction.normalized, out RaycastHit tempHit, maxDistance, audioManagerSettings.autoGeneratedWallLayerMask))
        {
            hitinfo = tempHit;
            return true;
        }

        return false;
    }

    private void AssignNewCutoffFreqToCurrentSource(AudioLowPassFilter _lowPassFilter, RaycastHit _hitinfo)
    {
        if (_lowPassFilter == null || dictionaryProvider.WallLayerMaskDictionary == null) return;

        if (dictionaryProvider.WallLayerMaskDictionary.TryGetValue(_hitinfo.transform.gameObject.layer, out float targetValue))
        {
            _lowPassFilter.cutoffFrequency = targetValue;
            Debug.Log($"Layer: {_hitinfo.transform.gameObject.layer} with Freq: {targetValue} was assigned (hard).");
        }
    }

    private void StopCurrentAudioSource(AudioDataObject _audioDataObject)
    {
        if (_audioDataObject == null || _audioDataObject.PoolIndex == -1 || !_audioDataObject.canHandleAudioSource)
            return;

        // DIE PERFORMANTE REVOLUTION: Kein Schleifen-Suchen mehr nötig!
        int targetIndex = _audioDataObject.PoolIndex;

        sourceProvider.allAudioSources[targetIndex].Source.Stop();

#if !USE_UNITASK
        if (audioManagerSettings.activeCoroutineChecks.TryGetValue(targetIndex, out Coroutine runningCoroutine))
        {
            if (runningCoroutine != null) StopCoroutine(runningCoroutine);
            audioManagerSettings.activeCoroutineChecks.Remove(targetIndex);
        }
#else
        sourceProvider.poolTokenSources[targetIndex].Cancel();
#endif
        _audioDataObject.PoolIndex = -1;
    }

    private void GenerateLayerMaskFromDictionary()
    {
        int combinedBitmask = 0;

        if (dictionaryProvider.WallLayerMaskDictionary != null)
        {
            foreach (int layerKey in dictionaryProvider.WallLayerMaskDictionary.Keys)
            {
                int layerBit = 1 << layerKey;
                combinedBitmask |= layerBit;
            }
        }

        audioManagerSettings.autoGeneratedWallLayerMask = combinedBitmask;
    }

    private void OnDestroy()
    {
#if !USE_UNITASK
        foreach (var runningCoroutine in audioManagerSettings.activeCoroutineChecks.Values)
        {
            if (runningCoroutine != null) StopCoroutine(runningCoroutine);
        }
        audioManagerSettings.activeCoroutineChecks.Clear();
#else
        linkedMasterTokenSource.Cancel();
        linkedMasterTokenSource.Dispose();

        for (int i = 0; i < sourceProvider.poolTokenSources.Length; i++)
        {
            if (sourceProvider.poolTokenSources[i] != null) sourceProvider.poolTokenSources[i].Dispose();
        }
#endif
    }
}