#define USE_UNITASK
using UnityEngine;
using System.Threading;
using System.Collections.Generic;

#if USE_UNITASK
using Cysharp.Threading.Tasks;
#endif

[CreateAssetMenu(fileName = "AudioManagerSettings", menuName = "Scriptable Objects/AudioManagerSettings")]


public class AudioManagerSettings : ScriptableObject
{
    [Header("General Values for both Methods")]
    [SerializeField][Range(1, 100)] public int numberOfAudioObjects = 50;
    [Space]
    public float defaultCuttoffFreqValue = 5000f;
    [Space]
    public AudioVolumesTransferObject transferObject;
    [Space]
    public GameObject audioGameObjectPrefab;
    [Space]
    public CutoffFreqLayerBehaviour[] CutoffFrequenciesPerLayer;
    [Space]
    public Transform playerAudioListenerTransform;
    [Space]
    [Range(0.01f, 1f)] public float timeIntervalBetweenPositionChecks = 0.25f;

    [HideInInspector] public LayerMask autoGeneratedWallLayerMask;
}
