//#define USE_UNITASK //TODO: REMOVE THIS!!!
using System;
using UnityEngine;
using System.Threading;
using System.Collections.Generic;


#if USE_UNITASK
using Cysharp.Threading.Tasks;
#endif
public class AudioManagerDataService : MonoBehaviour 
{
    [Header("General Values for both Methods")]
    [SerializeField][Range(1, 100)] public int numbersOfAudioSources = 50;
    [Space]
    public float defaultCuttoffFreqValue = 5000f;
    [Space]
    public AudioVolumesTransferObject transferObject;
    [Space]
    public GameObject audioGameObjectPrefab;
    [Space]
    public CutoffFreqLayerBehaviour[] CutoffFrequenciesPerLayer;
    [Space]
    public Transform playerAudioListenerTransform;
    [Space]
    [Range(0.01f, 1f)] public float timeIntervalBetweenPositionChecks = 0.25f;

    [HideInInspector] public LayerMask autoGeneratedWallLayerMask;

    private AudioManagerDictionaryProvider dictionaryProvider = new AudioManagerDictionaryProvider();

#if !USE_UNITASK
    [Header("Coroutine specific values")]
    public Dictionary<int, Coroutine> activeCoroutineChecks = new Dictionary<int, Coroutine>();
    public WaitForSeconds intervalWait;
    public WaitForSeconds pauseWait;
#else
    [Header("UniTask specific values")]
    public CancellationTokenSource linkedMasterTokenSource;
#endif
}
